format_version: 10
pipelines:
  Yaml_Test:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-02b95d1:
        git: https://github.com/cferguson04/Helloworld.git
        username: ''
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - Build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: true
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Build:
            timeout: 0
            artifacts:
              - build:
                source: ./*.nupkg
            tasks:
            - exec:
                arguments:
                - restore
                command: dotnet
                run_if: passed
            - exec:
                arguments:
                - build
                command: dotnet
                run_if: passed
            - exec:
                arguments:
                - pack -o ./
                command: dotnet
                run_if: passed
